/**
 * src/server/auth/cryptoUtils.ts
 *
 * Edge-compatible Web Crypto API password hashing and token generation.
 * Works uniformly in Cloudflare Workers, Pages Functions, browser, and Node.js.
 */

/**
 * Generates a cryptographically random hex salt.
 */
export function generateSalt(byteLength = 16): string {
  const bytes = new Uint8Array(byteLength);
  crypto.getRandomValues(bytes);
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}

/**
 * Generates a secure random session or unsubscribe token.
 */
export function generateToken(byteLength = 32): string {
  const bytes = new Uint8Array(byteLength);
  crypto.getRandomValues(bytes);
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}

/**
 * Hashes a password with salt using PBKDF2 (HMAC-SHA256, 100,000 iterations).
 * Completely standard Web Crypto implementation with no native binary dependencies.
 */
export async function hashPasswordPBKDF2(password: string, salt: string): Promise<string> {
  const enc = new TextEncoder();
  const passwordKey = await crypto.subtle.importKey(
    'raw',
    enc.encode(password),
    { name: 'PBKDF2' },
    false,
    ['deriveBits']
  );

  const derivedBits = await crypto.subtle.deriveBits(
    {
      name: 'PBKDF2',
      salt: enc.encode(salt),
      iterations: 100000,
      hash: 'SHA-256'
    },
    passwordKey,
    256 // 32 bytes = 256 bits
  );

  return Array.from(new Uint8Array(derivedBits))
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}

/**
 * Backward compatibility check for legacy scrypt hashes generated by older Node versions.
 */
function verifyLegacyScryptSync(password: string, salt: string, storedHash: string): boolean {
  try {
    // Only attempt if in Node environment with node:crypto
    const nodeCrypto = (globalThis as any).process?.versions?.node ? require('node:crypto') : null;
    if (nodeCrypto && typeof nodeCrypto.scryptSync === 'function') {
      const computed = nodeCrypto.scryptSync(password, salt, 64).toString('hex');
      return computed === storedHash;
    }
  } catch {
    // Ignore in non-Node environments
  }
  return false;
}

/**
 * Verifies a password against the stored hash and salt.
 */
export async function verifyPassword(
  password: string,
  salt: string,
  storedHash: string,
  algorithm: string = 'pbkdf2_sha256'
): Promise<boolean> {
  if (algorithm === 'pbkdf2_sha256') {
    const computed = await hashPasswordPBKDF2(password, salt);
    return computed === storedHash;
  }

  // Check legacy scrypt
  if (algorithm === 'scrypt') {
    return verifyLegacyScryptSync(password, salt, storedHash);
  }

  // Fallback try PBKDF2 then scrypt
  const computed = await hashPasswordPBKDF2(password, salt);
  if (computed === storedHash) return true;
  return verifyLegacyScryptSync(password, salt, storedHash);
}
